//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleForNetWebService.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://ws", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws", ConfigurationName="DataService.DataServicePortType")]
    public interface DataServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        VehicleForNetWebService.DataService.ArrayOfString getLst(string in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string writeObjectOut(string xtlb, string jkxlh, string jkid, string WriteXmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string queryObjectOut(string xtlb, string jkxlh, string jkid, string QueryXmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string exePro_18C55(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string exePro(string in0);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServicePortTypeChannel : VehicleForNetWebService.DataService.DataServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServicePortTypeClient : System.ServiceModel.ClientBase<VehicleForNetWebService.DataService.DataServicePortType>, VehicleForNetWebService.DataService.DataServicePortType {
        
        public DataServicePortTypeClient() {
        }
        
        public DataServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VehicleForNetWebService.DataService.ArrayOfString getLst(string in0) {
            return base.Channel.getLst(in0);
        }
        
        public string writeObjectOut(string xtlb, string jkxlh, string jkid, string WriteXmlDoc) {
            return base.Channel.writeObjectOut(xtlb, jkxlh, jkid, WriteXmlDoc);
        }
        
        public string queryObjectOut(string xtlb, string jkxlh, string jkid, string QueryXmlDoc) {
            return base.Channel.queryObjectOut(xtlb, jkxlh, jkid, QueryXmlDoc);
        }
        
        public string exePro_18C55(string in0, string in1) {
            return base.Channel.exePro_18C55(in0, in1);
        }
        
        public string exePro(string in0) {
            return base.Channel.exePro(in0);
        }
    }
}
